version: '3'

services:
  mysql:
    image: mysql:latest
    container_name: mysql_container_Doctor
    networks:
      - network-backend
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_DATABASE: database
      MYSQL_USER: user
      MYSQL_PASSWORD: 123456
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql


networks:
  network-backend:
    driver: bridge

volumes:
  mysql_data: